{% set name = "ijson" %}
{% set version = "3.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7f172e6ba1bee0d4c8f8ebd639577bfe429dee0f3f96775a067b8bae4492d8a0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  # Remove it when yajl backend will work on windows
  missing_dso_whitelist:
    - $RPATH/yajl.dll  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    - wheel
    - yajl 2.1.0
  run:
    - python
    - yajl >=2.1.0,<3.0.0

test:
  imports:
    - ijson
    - ijson.backends
  requires:
    - pip
  commands:
    - pip check
    - python -c "import ijson; assert ijson.backend == 'yajl2_c'"  # [not win]

about:
  home: https://github.com/ICRAR/ijson
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Ijson is an iterative JSON parser with a standard Python iterator interface.
  description: Ijson is an iterative JSON parser with standard Python iterator interfaces.
  doc_url: https://github.com/ICRAR/ijson
  dev_url: https://github.com/ICRAR/ijson

extra:
  recipe-maintainers:
    - rmax
    - thermokarst
