{% set name = "ijson" %}
{% set version = "2.4" %}
{% set sha256sum = "b78bbb5617716ebf47aff67932bee4ec811909ef69b93c3925b2fe1f0fe4b98c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - ijson

about:
  home: https://github.com/isagalaev/ijson
  license: BSD 3-clause
  license_file: LICENSE.txt
  summary: Ijson is an iterative JSON parser with a standard Python iterator interface.
  doc_url: https://github.com/isagalaev/ijson
  dev_url: https://github.com/isagalaev/ijson

extra:
  recipe-maintainers:
    - rmax
    - thermokarst
