# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "RRM6B/iL81YW0uXlJ3sQZuODfTq6R4heq2wuWvXkAJ0cOcQYF0em/cUW9GcHSLVdFEH3qNK/Afp8HsmA7+99dtbNvtYXErkmKA4AH3WwHJch+sB8ZAh2hWXYBCODGNjadTBD+gvojNeU3m5awWq+e0Q4pkxusaYni/+aUrP2awBoWtg79w1xxAiFFMmeDa1Bqz+oUyzhqJ7TiM70Ods6081sFNrwUsRmKg1nHcsZ5WwceWoSbyhmzYeqCyHpDIaUVRQ4iUDaqQLFgclgaksBQUSiNNgEydzRc1tmiLkEP4odavqKWGEurWG3ObXb6a8JwLn5WBKMD0q1xFCXl1iW2TBEHVi2vktW/G0qn7/hFOdlgLj1Br7k4k3GS9Xr85JaQUkW6stgaNniYmwt8fDaDt3vGZZAO0IEDtKKjb22gXVdp5gXikePo6vrGlb9/tLLBwEFOR+IecToOSZbB4BGf19fP4hliiIdtmzsWOMNpDD5qVuKuutrtSaUFaQJgAEUBgjlKUc3Cp7OHfb2/R3gEqHvXv1Z1H1+Zy/M0Xeb88SO6QYXhWRe81SqmWTkUAo6Ozw9m6plD7NrNYlk86W8QVmJgub/4/ccxrrzouHY913Gdd9csegMszaAdrOwoReiVqYg+LLcauExPtngP6zrqdCmtEGxw8JsDW//nDUcFbM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
