travis:
  secure:
    BINSTAR_TOKEN: 3Tw+1MkEptPpltHUFvt2vjhev7Sc/DfKA1SWBi2AZeoZhbwF0c0YsuXc3x/IxpNOIXgYDAyJ0HDCafGP+zIejkh+6F+XC1gtXAzYLUYrhOW7PVErlub7m2Qw/VLC5TTC6SFqT7SlAlidKn7Q75u6VeuO1I4LTD84itedJOw6HyD9MDhzSyS6MrpdZduL593KbHlOEIkSOyvN1gzUWUK11Vhiy3PeQn9416kcVT6OSZNU0nZMMjUKCo/420TBVN8gW3jk47m1f7g6xwciAu+v4TVQAL2EPwBFwysqwBk8gBu7sqJYqRyk0aOTwZ8GaehSqHv+GMBh4UOx8Ne9qtwUCQQTLd5CjiZ/WLXJXdVH1/o69vPWM5aIsF7WgkeI9QS4eONu7zVuognXgoZgu2IzZpKxnkriEKqUvlwZmvSQfG6mQlH9NoVHEtm2i19r/ig6nxMad6NzeQuFWylDUA+IlGHGe7xEmrNgt3x89+h2knNgKKaxcs0KZOzd+pWZYadmXz/aK3nvusly5du5a2eaJFiEC/F9zFHZuxfdKp8ejpJL5NatYYCSwrC21/YQPoeATiaueapJmE5wIa6l5ZDMR4UlSWquESOiEv1tRI1Kqvi1X6OYXO6zyAikSOlBCNA6lzGULtJ1AFN8LSqVW+fDvlmCvbGntP3kMd6rQOmngUo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
