travis:
  secure:
    BINSTAR_TOKEN: RRM6B/iL81YW0uXlJ3sQZuODfTq6R4heq2wuWvXkAJ0cOcQYF0em/cUW9GcHSLVdFEH3qNK/Afp8HsmA7+99dtbNvtYXErkmKA4AH3WwHJch+sB8ZAh2hWXYBCODGNjadTBD+gvojNeU3m5awWq+e0Q4pkxusaYni/+aUrP2awBoWtg79w1xxAiFFMmeDa1Bqz+oUyzhqJ7TiM70Ods6081sFNrwUsRmKg1nHcsZ5WwceWoSbyhmzYeqCyHpDIaUVRQ4iUDaqQLFgclgaksBQUSiNNgEydzRc1tmiLkEP4odavqKWGEurWG3ObXb6a8JwLn5WBKMD0q1xFCXl1iW2TBEHVi2vktW/G0qn7/hFOdlgLj1Br7k4k3GS9Xr85JaQUkW6stgaNniYmwt8fDaDt3vGZZAO0IEDtKKjb22gXVdp5gXikePo6vrGlb9/tLLBwEFOR+IecToOSZbB4BGf19fP4hliiIdtmzsWOMNpDD5qVuKuutrtSaUFaQJgAEUBgjlKUc3Cp7OHfb2/R3gEqHvXv1Z1H1+Zy/M0Xeb88SO6QYXhWRe81SqmWTkUAo6Ozw9m6plD7NrNYlk86W8QVmJgub/4/ccxrrzouHY913Gdd9csegMszaAdrOwoReiVqYg+LLcauExPtngP6zrqdCmtEGxw8JsDW//nDUcFbM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
